#%RAML 1.0
title: Origami
version: 1
baseUri: /api/v1/

# types:
#   UserPost: !include routes/user/shapes.raml
uses:
  user: routes/user/types.raml

resourceTypes:
  collection: !include resourceTypes/collection.type.raml
  collection-item: !include resourceTypes/collection-item.type.raml



securitySchemes:
  JWT:
    type: x-{other}
    describedBy:
      headers:
        Authorization:
          description: X-AuthToken
          type: string
          required: true
      responses:
        401:
          description: Authentication problem (JWT not set or invalid)

/auth:
  /login:
    post:
      body:
        application/json:
          properties:
            email:
              type: string
            password:
              type: string
      responses:
        200:
          body:
            application/json: |
                {
                    "statusCode": 200,
                    "data": {
                        "token": "fyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZWJkNjRlMS04ODMwLTQ3ZjktOTJiYy1mMzZiNGNlZjBmYjYiLCJlbWFpbCI6InRyaXN0YW5Ab3JpZ2FtaWNtcy5jb20iLCJpYXQiOjE1MDY1MTI3ODYsImV4cCI6MTUwNjUxNDU4Nn0.k_gxaq5uYlbg8m6bLlBqSO4HelmwDx4jxMPknGnw34E",
                        "expires": 1506512786
                    }
                }
  /verify:
    securedBy: JWT
    get:
  /refresh:
    securedBy: JWT
    post:

/users:
  type: collection
  post:
    body:
      application/json:
        properties:
          fname:
            type: string
          lname:
            type: string
          email:
            type: string
          password:
            type: string

    responses:
      201:
        body:
          application/json: !include routes/user/responses/post.201.json

  /:userId:
    type: collection-item
    get:
      responses:
        200:
          body:
            application/json: !include routes/user/responses/get.200.json

/pages:
  type: collection
  /types:
    get:
  /:pageId:
    type: collection-item
    /properties:
      get:
      put:

/templates:
  type: collection
  /:templateName:
    type: collection-item

/themes:
  get:
  /installed:
    get:
  /install:
    post:
  /activate/:themeName:
    post:

/settings:
  get:
  post:
  /:setting:
    get:
    delete:
    put:
