#%RAML 1.0 Resource

type: !include ../../resourceTypes/collection.type.raml
post:
  body:
    application/json:
      properties:
        fname:
          type: string
        lname:
          type: string
        email:
          type: string
        password:
          type: string

/:userId:
  type: !include ../../resourceTypes/collection-item.type.raml
  put:
    responses:
      200:
        body:
          application/json: !include responses/users/put.200.json
